// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vIMr3J_O0suR1Gfv0kS1oHjZVu2M_Vs',
    appId: '1:1087253900363:web:bc639ad2285228081031ce',
    messagingSenderId: '1087253900363',
    projectId: 'flutter-crud-application-3f0cd',
    authDomain: 'flutter-crud-application-3f0cd.firebaseapp.com',
    databaseURL: 'https://flutter-crud-application-3f0cd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-3f0cd.firebasestorage.app',
    measurementId: 'G-24CGPYSMET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQDn2LVfYxpK-to1xo8R4ob2dm8w_ObZs',
    appId: '1:1087253900363:android:9d181465e59d84bf1031ce',
    messagingSenderId: '1087253900363',
    projectId: 'flutter-crud-application-3f0cd',
    databaseURL: 'https://flutter-crud-application-3f0cd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-3f0cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZN1N0YK7AY5UyX8ksfUUrJ_ND1tA-DF4',
    appId: '1:1087253900363:ios:21654d128a16c61c1031ce',
    messagingSenderId: '1087253900363',
    projectId: 'flutter-crud-application-3f0cd',
    databaseURL: 'https://flutter-crud-application-3f0cd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-3f0cd.firebasestorage.app',
    iosBundleId: 'com.example.roleBasedLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZN1N0YK7AY5UyX8ksfUUrJ_ND1tA-DF4',
    appId: '1:1087253900363:ios:21654d128a16c61c1031ce',
    messagingSenderId: '1087253900363',
    projectId: 'flutter-crud-application-3f0cd',
    databaseURL: 'https://flutter-crud-application-3f0cd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-3f0cd.firebasestorage.app',
    iosBundleId: 'com.example.roleBasedLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-vIMr3J_O0suR1Gfv0kS1oHjZVu2M_Vs',
    appId: '1:1087253900363:web:e2387aa142ca6dad1031ce',
    messagingSenderId: '1087253900363',
    projectId: 'flutter-crud-application-3f0cd',
    authDomain: 'flutter-crud-application-3f0cd.firebaseapp.com',
    databaseURL: 'https://flutter-crud-application-3f0cd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-3f0cd.firebasestorage.app',
    measurementId: 'G-4P1R3MF2C7',
  );
}
